# Author : Fayzer789

def intro():
    print("zzzzzzzzzzzzzzzzz")
    print("*alarm clock noise* DRINGGGGGGG")
    print("WHatttt can't you let me sleep just a little bit man")
    print("*you disable the alarm*")
    print("*You scratch your eyes with your hands for a bit and get up*")
    print("Fuck off I was getting extra good sleep if only that damn thing hadn’t woken me up")
    print("*You look at the window")
    print("Oh that's weird what is it already the night?")
    print("Wait")
    print("...")
    print("Don't tell me")
    print("............")
    print("IT'S ALREADY 9 PM")
    print("I’M 20 MINUTES LATE FOR THE BIG CRUISE MEAL")
    print("*you dress so fast that you have completely forgotten your tie*")
    print("I hope I won't be in late")
    print("*you're running as fast you can to not get too late*")
    print("...But")
    print("suddenly a loud noise is heard..")
    print("BAMMMMMMMMMM")
    print("It was a sudden collision that made the whole ship vibrate")
    print("Lights go off and a piercing red alarm starts to ring in your ears")
    print("        *****************************************")
    print("        *                                       *")
    print("        *            Escape Titanic             *")
    print("        *                                       *")
    print("        *****************************************")

